name: ğŸš€  Deployment
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_LIGHTSAIL_SERVICE_NAME: photoscavenger-backend-service

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  buildcontainers:
    name: ğŸš€ Build and Deploy Containers to AWS Lightsail
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—‚ Checkout repository
        uses: actions/checkout@v2

      - name: âš™ï¸ Update packages
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: ğŸ¤ Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REDIS_URL: ${{ secrets.REDIS_URL }}
          file_name: .env
          fail_on_empty: false

      - name: ğŸ¢ Install AWS CLI and Lightsail CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: ğŸ¤ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ğŸ›  Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver: docker-container

      - name: ğŸ³ Build Docker image with aggressive caching
        uses: docker/build-push-action@v4
        with:
          context: ./.deployment
          file: ./.deployment/dockerfile
          push: false
          tags: fastapi:latest
          builder: default
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:docker-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:docker-cache,mode=max

      - name: ğŸ“¬ Push image to AWS Lightsail container registry
        run: |
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${AWS_LIGHTSAIL_SERVICE_NAME} \
            --label fastapi \
            --image fastapi:latest

      - name: ğŸš€ Deploy container to Lightsail
        run: |
          aws lightsail create-container-service-deployment \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --containers file://.deployment/AWS/deploymentconfig.json \
            --public-endpoint file://.deployment/AWS/publicendpoint.json
